name: Build the FCC zim file

on: push
jobs:
  build_zim_file:
    runs-on: ubuntu-latest
    name: Install dependencies with pip
    defaults:
        run:
          working-directory: openzim
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        cache: 'pip' # caching pip dependencies
    - run: pip install -r requirements.txt
      working-directory: openzim

    - uses: actions/setup-node@v3
      with:
        node-version: 18
        cache: 'yarn'
        cache-dependency-path: '**/yarn.lock'
    - run: yarn install --frozen-lockfile
      working-directory: client
    - run: yarn lint
      working-directory: client
    - run: yarn test
      working-directory: client
