name: Build the FCC zim file

on: push
jobs:
  build_python:
    runs-on: ubuntu-latest
    name: Install dependencies with pip
    defaults:
        run:
          working-directory: openzim
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        cache: 'pip' # caching pip dependencies
    - run: pip install -r requirements.txt
  build_node:
    runs-on: ubuntu-latest
    name: Install dependencies with yarn
    steps:
    - uses: actions/setup-node@v3
      with:
        node-version: 18
    - run: yarn install
    - run: yarn lint
    - run: yarn test
